from __future__ import annotations

DEFAULT_LLM_MODEL = "openai-chat:google/gemma-4-31b-qat"
DEFAULT_LLM_BASE_URL = "http://host.docker.internal:1234/v1"
DEFAULT_LLM_TIMEOUT_SECONDS = 600
DEFAULT_MAX_CONCURRENT_AGENTS = 1
DEFAULT_AGENT_REQUEST_LIMIT = 200
DEFAULT_AGENT_TOOL_CALLS_LIMIT = 200
